# Generated by Django 6.1 on 2026-08-25 17:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('description', models.TextField()),
                ('issue_category', models.CharField(choices=[('AGRIC', 'Agriculture'), ('HEALTH', 'Healthcare'), ('SECURITY', 'Security'), ('INFRA', 'Infrastructure'), ('WATER', 'Water & Sanitation')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RAW', 'Raw Observation'), ('AI_PROCESSED', 'AI Processed'), ('PENDING_VERIFICATION', 'Pending Field Verification'), ('VERIFIED', 'Verified Intelligence'), ('REJECTED', 'Rejected/Invalid')], default='RAW', max_length=20)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_suggested_category', models.CharField(blank=True, max_length=50)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insight.lga')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_file', models.FileField(upload_to='evidence/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('AUD', 'Audio')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_set', to='insight.report')),
            ],
        ),
    ]
