# Generated by Django 6.1 on 2026-08-25 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_report_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('RAW', 'Raw Observation'), ('AI_PROCESSED', 'AI Processed'), ('PENDING_VERIFICATION', 'Pending Field Verification'), ('VERIFIED', 'Verified Intelligence'), ('REJECTED', 'Rejected/Invalid'), ('INTERVENTION_PLANNED', 'Intervention Planned'), ('RESOLVED', 'Resolved')], default='RAW', max_length=20),
        ),
        migrations.CreateModel(
            name='FieldAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_lgas', models.ManyToManyField(blank=True, related_name='field_agents', to='insight.lga')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_notes', models.TextField(blank=True)),
                ('verification_photos', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Agent'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected - Invalid Report')], default='PENDING', max_length=20)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='insight.fieldagent')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_verification', to='insight.report')),
            ],
        ),
    ]
