# Generated by Django 6.1 on 2026-08-27 12:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_alter_report_status_fieldagent_fieldverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldagent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='report',
            name='ai_extracted_entities',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_urgency_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='evidence_set',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='fieldagent',
            name='agent_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldagent',
            name='assigned_lgas',
            field=models.ManyToManyField(blank=True, to='insight.lga'),
        ),
        migrations.AlterField(
            model_name='fieldagent',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldagent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldverification',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fieldverification',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='insight.report'),
        ),
        migrations.AlterField(
            model_name='fieldverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldverification',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_suggested_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='issue_category',
            field=models.CharField(choices=[('WATER', 'Water'), ('HEALTH', 'Health'), ('AGRIC', 'Agriculture'), ('SECURITY', 'Security'), ('INFRA', 'Infrastructure'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='lga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='insight.lga'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('RAW', 'Raw Observation'), ('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified Intelligence'), ('DISCARDED', 'Discarded')], default='RAW', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
