# Generated by Django 6.1 on 2026-08-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004a_fill_ai_nulls'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded image from mobile app', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_suggested_category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
