# Generated by Django 6.1 on 2026-09-03 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_remove_fieldagent_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded image from mobile app', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_suggested_category',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IntelligenceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily SITREP'), ('WEEKLY', 'Weekly Intelligence Summary'), ('FLASH', 'Flash Alert')], default='DAILY', max_length=20)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('executive_briefing', models.TextField(blank=True, default='')),
                ('key_findings', models.JSONField(blank=True, default=list)),
                ('emerging_threats', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('source_reports', models.ManyToManyField(blank=True, related_name='intelligence_summaries', to='insight.report')),
            ],
            options={
                'verbose_name_plural': 'Intelligence Summaries',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PatternAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('SURGE', 'Report Volume Surge'), ('CLUSTER', 'Geographic Clustering'), ('ESCALATION', 'Urgency Escalation')], default='SURGE', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('pattern_data', models.JSONField(blank=True, default=dict)),
                ('acknowledged', models.BooleanField(default=False)),
                ('related_reports', models.ManyToManyField(blank=True, related_name='pattern_alerts', to='insight.report')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
