# Generated by Django 6.1 on 2026-09-06 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0005_report_image_base64_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('AIRTIME', 'Airtime / Data Bundle'), ('MATERIAL', 'Physical Materials'), ('SCHOLARSHIP', 'Scholarship / Education'), ('CASH', 'Cash Reward'), ('BADGE', 'Digital Badge / Award')], max_length=20)),
                ('points_required', models.IntegerField(help_text='Points needed to redeem')),
                ('min_tier_required', models.CharField(choices=[('CITIZEN', 'Citizen'), ('VOLUNTEER', 'Vetted Volunteer'), ('INFORMANT', 'Covert Informant'), ('AGENT', 'Official Field Agent')], default='CITIZEN', help_text='Minimum user tier to redeem', max_length=20)),
                ('quantity_available', models.IntegerField(default=-1, help_text='-1 means unlimited')),
                ('is_active', models.BooleanField(default=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Reward Catalog',
                'ordering': ['points_required'],
            },
        ),
        migrations.AlterField(
            model_name='lga',
            name='state',
            field=models.CharField(default='Taraba', max_length=100),
        ),
        migrations.RemoveField(
            model_name='ward',
            name='lga',
        ),
        migrations.AlterModelOptions(
            name='fieldverification',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AlterModelOptions(
            name='intelligencesummary',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='fieldagent',
            name='assigned_lgas',
        ),
        migrations.RemoveField(
            model_name='fieldagent',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='fieldagent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fieldverification',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='fieldverification',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='fieldverification',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='fieldverification',
            name='verification_photos',
        ),
        migrations.RemoveField(
            model_name='intelligencesummary',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='intelligencesummary',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='intelligencesummary',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='intelligencesummary',
            name='source_reports',
        ),
        migrations.RemoveField(
            model_name='patternalert',
            name='pattern_data',
        ),
        migrations.RemoveField(
            model_name='report',
            name='evidence_set',
        ),
        migrations.AddField(
            model_name='fieldagent',
            name='assigned_lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insight.lga'),
        ),
        migrations.AddField(
            model_name='fieldagent',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldverification',
            name='is_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldverification',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intelligencesummary',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lga',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='acknowledgment_sent',
            field=models.BooleanField(default=False, help_text='Has the user been notified of receipt?'),
        ),
        migrations.AddField(
            model_name='report',
            name='intel_quality_score',
            field=models.IntegerField(default=0, help_text='AI graded quality: 0 to 100'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_covert',
            field=models.BooleanField(default=False, help_text='Submitted via discreet/panic mode'),
        ),
        migrations.AddField(
            model_name='report',
            name='points_awarded',
            field=models.IntegerField(default=0, help_text='Points granted for this specific report'),
        ),
        migrations.AddField(
            model_name='report',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='The user who submitted this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldverification',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insight.fieldagent'),
        ),
        migrations.AlterField(
            model_name='fieldverification',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fieldverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='intelligencesummary',
            name='emerging_threats',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='intelligencesummary',
            name='executive_briefing',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intelligencesummary',
            name='key_findings',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='intelligencesummary',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='intelligencesummary',
            name='statistics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='intelligencesummary',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patternalert',
            name='alert_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patternalert',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patternalert',
            name='related_reports',
            field=models.ManyToManyField(blank=True, to='insight.report'),
        ),
        migrations.AlterField(
            model_name='patternalert',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='patternalert',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_extracted_entities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_suggested_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_urgency_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='issue_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insight.lga'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('RAW', 'Raw'), ('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='RAW', max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('CITIZEN', 'Citizen'), ('VOLUNTEER', 'Vetted Volunteer'), ('INFORMANT', 'Covert Informant'), ('AGENT', 'Official Field Agent')], default='CITIZEN', max_length=20)),
                ('total_points', models.IntegerField(default=0, help_text='Current available reward points')),
                ('lifetime_points', models.IntegerField(default=0, help_text='Total points earned historically')),
                ('phone_number', models.CharField(blank=True, help_text='For SMS acknowledgments and rewards', max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Has an admin vetted this user?')),
                ('use_codename', models.BooleanField(default=False)),
                ('codename', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intel_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles & Tiers',
            },
        ),
        migrations.CreateModel(
            name='RewardLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARNED_SUBMISSION', 'Points Earned: Report Submitted'), ('EARNED_ACTIONABLE', 'Points Earned: Intel Graded Actionable'), ('EARNED_VERIFIED', 'Points Earned: Intel Physically Verified'), ('REDEEMED_AIRTIME', 'Points Redeemed: Airtime/Data'), ('REDEEMED_MATERIAL', 'Points Redeemed: Physical Materials'), ('REDEEMED_SCHOLARSHIP', 'Points Redeemed: Scholarship/Education'), ('REDEEMED_CASH', 'Points Redeemed: Cash Reward'), ('REDEEMED_BADGE', 'Points Redeemed: Digital Badge'), ('ADMIN_ADJUSTMENT', 'Admin Manual Adjustment')], max_length=30)),
                ('points', models.IntegerField(help_text='Positive for earned, negative for redeemed')),
                ('description', models.TextField(blank=True, help_text='Reason for transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insight.report')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='insight.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Reward Ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_deducted', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=20)),
                ('delivery_details', models.TextField(blank=True, help_text='Phone number, address, bank details, etc.')),
                ('admin_review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='insight.rewardcatalog')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='insight.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PollingUnit',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
