# Generated by Django 6.1 on 2026-09-22 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0007_agentregistrationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='auto_flagged_critical',
            field=models.BooleanField(default=False, help_text='Auto-escalated by keyword detection'),
        ),
        migrations.AddField(
            model_name='report',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agentregistrationrequest',
            name='lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='acknowledgment_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_confidence_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_extracted_entities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_urgency_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MODERATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded image', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='intel_quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_covert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('RAW', 'Raw Submission'), ('PROCESSED', 'AI Processed'), ('VERIFIED', 'Field Verified'), ('REJECTED', 'Rejected')], default='RAW', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
