# Generated by Django 6.1 on 2026-09-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0008_report_ai_summary_report_auto_flagged_critical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencesummary',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intelligencesummary',
            name='statistics',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
