# Generated by Django 6.1 on 2026-09-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0009_intelligencesummary_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intelligencesummary',
            options={'verbose_name_plural': 'Intelligence Summaries'},
        ),
        migrations.RemoveField(
            model_name='intelligencesummary',
            name='emerging_threats',
        ),
        migrations.RemoveField(
            model_name='intelligencesummary',
            name='executive_briefing',
        ),
        migrations.RemoveField(
            model_name='intelligencesummary',
            name='key_findings',
        ),
        migrations.RemoveField(
            model_name='intelligencesummary',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='intelligencesummary',
            name='report_count',
        ),
        migrations.AlterField(
            model_name='intelligencesummary',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
