# Generated by Django 6.1 on 2026-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0010_alter_intelligencesummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.CharField(choices=[('TARABA', 'Taraba State'), ('DELTA', 'Delta State')], default='TARABA', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('TARABA', 'Taraba State'), ('DELTA', 'Delta State')], default='TARABA', max_length=20),
        ),
        migrations.AlterField(
            model_name='lga',
            name='state',
            field=models.CharField(choices=[('TARABA', 'Taraba State'), ('DELTA', 'Delta State')], default='TARABA', max_length=20),
        ),
    ]
